# Generated by Django 4.1 on 2023-04-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=150)),
            ],
        ),
    ]
