# Generated by Django 4.1 on 2023-04-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_rename_inclusion_date_photo_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='filename',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
