# Generated by Django 4.1 on 2023-04-07 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photo_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='inclusion_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
