# Generated by Django 4.1 on 2023-04-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_photo_inclusion_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='inclusion_date',
            new_name='date_added',
        ),
    ]
