# Generated by Django 4.1 on 2023-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
