# Generated by Django 4.1 on 2023-04-26 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_photo_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 23, 38, 52, 262847, tzinfo=datetime.timezone.utc)),
        ),
    ]
