# Generated by Django 4.1 on 2023-04-26 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_photo_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
